#
# Scyther makefile
#
# Scyther really uses the scons program (http://www.scons.org/), of
# which there is a local copy present. So this is just delegating stuff.
#
#
SCONS = ./scons.py

all:
	${SCONS} all

windows:
	${SCONS} windows

linux:
	${SCONS} linux

tags:
	${SCONS} tags

clean:
	${SCONS} -c

