#
# Scyther makefile
#
# Scyther really uses the scons program (http://www.scons.org/), of
# which there is a local copy present. So this is just delegating stuff.
#
#
all:
	./scons.py all

windows:
	./scons.py windows

linux:
	./scons.py linux

tags:
	./scons.py tags

