#!/bin/sh

./scyther $* >>output.txt

case $? in
	0) echo "./scyther $* : Noattack" >>done.txt;;
	1) echo "./scyther $* : ERROR" >>done.txt;;
	2) echo "./scyther $* : Noattack (no claims)" >>done.txt;;
	3) echo "./scyther $* : ATTACK" >>done.txt;;
esac
