#!/bin/bash
#
# Shell script to display the latex output relatively quickly. For
# internal testing only, as it depends on the spdl subdirectory.
#
# Usage example:
#
#	./scytherat ns3
#

file=../spdl/$1.spdl
template=../src/attacktemplate

if [ -f $file ]
then 
    ../src/scyther --latex $file -o attack.tex
    if [ "$?" -eq "3" ]
    then
        latex $template.tex
    
        mv $template.dvi attack.dvi
        #dvips attack.dvi -o attack.ps
    
        # also eps output now
        #ps2eps -f attack.ps
    
        xdvi attack.dvi		# for Xdvi
        #    kdvi attack.dvi		# for KDE environment
        #    kghostview attack.ps	# postscript in KDE
    fi
else

  echo "No file $file found."

fi


